---
title: "Introduction to computePI"
author: "Samer Mouksassi"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to computePI}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package enable you to quickly compute prediciton intervals on Observed and Simulated data to get the ouput needed to produce Visual Predictive Checks plots. It supports per strata binning, per strata lower limit of quantification and uses `data.table`for faster computations.

To get started:
```
devtools::install_github("smouksassi/computePI")
library(computePI)
```

## Figures



```{r, fig.show='hold', fig.height= 800}
require(ggplot2)
require(dplyr)
require(rlang)
require(vpc)
require(data.table)
require(computePI)

theme_set(theme_bw())
exampleobs <- simple_data$obs
exampleobs <- exampleobs[exampleobs$MDV == 0, ]
examplesim <- simple_data$sim
exampleobs$PRED <- examplesim[1:nrow(exampleobs), "PRED"]
exampleobs$REP <- 0
exampleobs$LLOQ <- 50
examplesim <- examplesim[examplesim$MDV == 0, ]#
examplesim$LLOQ <- 50
exampleobs$LLOQ <- ifelse(exampleobs$ISM == 0, 100, 25)
examplesim$LLOQ <- ifelse(examplesim$ISM == 0, 100, 25)

VPCDATA<- computePI(
  obsdata = exampleobs, simdata = examplesim, stratify = ~ISM,
  NBINS = NULL, LLOQ = LLOQ)

AAA <- ggplot(VPCDATA) +
  facet_wrap(~ISM, scales = "free_x", labeller = label_wrap_gen(multi_line = FALSE), ncol = 2) +
  geom_ribbon(aes(XMED,
                                ymin = (`DV2.5%CI`), ymax = (`DV97.5%CI`),
                                fill = DVQNAME, col = DVQNAME,
                                group = DVQNAME
  ), alpha = 0.1, col = NA) +
  geom_line(data = VPCDATA, aes(XMED,
                              y = `DV50%CI`,
                              col = DVQNAME, group = DVQNAME
  )) +
  geom_line(data = VPCDATA, aes(
    x = XMED, y = DVOBS, group = DVQNAME,
    linetype = DVQNAME
  ), size = 2) +
  geom_hline(yintercept = c(25,100), col = "green") +
  geom_rug(data = VPCDATA, aes(x = XMIN), sides = "t") +
  geom_rug(data = VPCDATA, aes(x = XMAX), sides = "t") +
  scale_colour_manual(
    name = "Simulated Percentiles\nMedian (lines) 95% CI (areas)",
    breaks = c("5%PI", "50%PI", "95%PI", "Percent BLQ"),
    values = c("red", "blue", "red", "black"),
    labels = c("5%", "50%", "95%", "Percent BLQ")
  ) +
  scale_fill_manual(
    name = "Simulated Percentiles\nMedian (lines) 95% CI (areas)",
    breaks = c("5%PI", "50%PI", "95%PI", "Percent BLQ"),
    values = c("red", "blue", "red", "black"),
    labels = c("5%", "50%", "95%", "Percent BLQ")
  ) +
  scale_linetype_manual(
    name = "Observed Percentiles\n(black lines)",
    breaks = c("5%PI", "50%PI", "95%PI"),
    values = c("dotted", "solid", "dashed"),
    labels = c("5%", "50%", "95%")
  ) +
  guides(
    fill = guide_legend(order = 2),
    colour = guide_legend(order = 2),
    linetype = guide_legend(order = 1)
  ) +
  theme(
    legend.position = "top", legend.key.width = grid::unit(1, "cm"),
    axis.text.x = element_text(angle = 30), axis.title.x = element_blank()
  ) 

BBB <- ggplot(VPCDATA[VPCDATA$DVQNAME == VPCDATA$DVQNAME[1], ]) +
  facet_wrap(~ISM, scales = "free_x", labeller = label_wrap_gen(multi_line = FALSE), ncol = 2) +
  geom_ribbon(data = VPCDATA, aes(XMED,
                                ymin = (`PCTBLQ2.5%CI`), ymax = (`PCTBLQ97.5%CI`),
                                fill = PCTBLQQNAME, col = PCTBLQQNAME,
                                group = PCTBLQQNAME
  ), alpha = 0.1, col = NA) +
  geom_line(data = VPCDATA, aes(XMED,
                              y = `PCTBLQ50%CI`,
                              col = PCTBLQQNAME, group = PCTBLQQNAME
  )) +
  geom_line(data = VPCDATA, aes(
    x = XMED, y = PCTBLQOBS, group = PCTBLQQNAME,
    linetype = PCTBLQQNAME
  ), size = 2) +
  geom_rug(data = VPCDATA, aes(x = XMIN), inherit.aes = FALSE, sides = "t") +
  geom_rug(data = VPCDATA, aes(x = XMAX), inherit.aes = FALSE, sides = "t") +
  scale_colour_manual(
    name = "Simulated Percentiles\nMedian (lines) 95% CI (areas)",
    breaks = c("5%PI", "50%PI", "95%PI", "PercentBLQ"),
    values = c("red", "blue", "red", "black"),
    labels = c("5%", "50%", "95%", "Percent BLQ")
  ) +
  scale_fill_manual(
    name = "Simulated Percentiles\nMedian (lines) 95% CI (areas)",
    breaks = c("5%PI", "50%PI", "95%PI", "PercentBLQ"),
    values = c("red", "blue", "red", "black"),
    labels = c("5%", "50%", "95%", "Percent BLQ")
  ) +
  scale_linetype_manual(
    name = "Observed Percentiles\n(black lines)",
    breaks = c("5%PI", "50%PI", "95%PI"),
    values = c("dotted", "solid", "dashed"),
    labels = c("5%", "50%", "95%")
  ) +
  guides(
    fill = guide_legend(order = 2),
    colour = guide_legend(order = 2),
    linetype = guide_legend(order = 1)
  ) +
  theme(
    legend.position = "bottom", legend.key.width = grid::unit(2, "cm"),
    axis.text.x = element_text(angle = 30), axis.title.x = element_blank()
  )

egg::ggarrange(AAA, BBB)

```

